name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install black flake8 isort pytest nbval
        
    - name: Lint with black
      run: black --check .
      
    - name: Lint with flake8
      run: flake8 .
      
    - name: Lint with isort
      run: isort --check-only --profile black .
      
    - name: Test notebooks
      run: pytest --nbval Interpretable_ML_Chris.ipynb

  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t xai-interpretable-ml .