name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install black flake8 isort
        
    - name: Validate repository structure
      run: |
        echo "Checking for key files..."
        [ -f "Makefile" ] && echo "✓ Makefile exists" || echo "✗ Makefile not found"
        [ -f "Dockerfile" ] && echo "✓ Dockerfile exists" || echo "✗ Dockerfile not found"
        [ -f "requirements.txt" ] && echo "✓ requirements.txt exists" || echo "✗ requirements.txt not found"
        [ -f "README.md" ] && echo "✓ README.md exists" || echo "✗ README.md not found"
        [ -f "Interpretable_ML_Chris.ipynb" ] && echo "✓ Notebook exists" || echo "✗ Notebook not found"
        
    - name: Lint with black
      continue-on-error: true
      run: black --check --diff .
      
    - name: Lint with flake8
      continue-on-error: true
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      
    - name: Lint with isort
      continue-on-error: true
      run: isort --check-only --diff --profile black .

  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t xai-interpretable-ml .